version: '3'

services:
  mongo1:
    image: mongo
    command: ["--replSet", "my.repl"]
    ports: 
        - "27017:27017"
    extra_hosts:
      - "mongo4:161.35.136.239"
    networks:
      - my-network
    depends_on:
      - mongo2
      - mongo3

  mongo2:
    image: mongo 
    command: ["--replSet", "my.repl"]
    ports: 
        - "27018:27017"
    networks:
      - my-network

  mongo3:
    image: mongo
    command: ["--replSet", "my.repl"]
    ports: 
        - "27019:27017"
    networks:
      - my-network
networks:
  my-network:
